// this is just an s3 deployment pipeline, its static. ecr + ecs deployment needs to be in this file.

//note* task-definition.json is a sample task definition for an ECS Fargate service. Replace <ACCOUNT_ID> and <IMAGE> with your actual values.**

pipeline {
    agent any

    environment {
        AWS_DEFAULT_REGION = 'us-east-1'
        ECR_REPO     = '160226155782.dkr.ecr.us-east-1.amazonaws.com/react-jenkins-cicd'
        ECS_CLUSTER   = 'react-jenkins-cluster-2'
        ECS_SERVICE   = 'react-jenkins-service'
    }

    stages {

        stage('Build') {
            agent {
                docker {
                    image 'node:22-alpine'
                    reuseNode true
                }
            }
            steps {
                sh '''
                    node --version
                    npm --version
                    npm ci
                    npm run build
                '''
            }
        }

        stage('Test') {
            agent {
                docker {
                    image 'node:22-alpine'
                    reuseNode true
                }
            }
            steps {
                sh '''
                    test -f build/index.html
                    echo "Build OK"
                    CI=true npm test
                '''
            }
        }

stage('Build My Docker Image') {
    steps {
        withCredentials([aws(accessKeyVariable: 'AWS_ACCESS_KEY_ID', credentialsId: 'reactAWS', secretKeyVariable: 'AWS_SECRET_ACCESS_KEY')]) {
            sh '''
                docker run --rm -e AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY --entrypoint="" amazon/aws-cli:2.34.14 aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REPO
                docker build -t $ECR_REPO:$BUILD_NUMBER .
                docker push $ECR_REPO:$BUILD_NUMBER
            '''
        }
    }
}

stage('Deploy to AWS') {
    agent {
        docker {
            image 'amazon/aws-cli:2.34.14'
            reuseNode true
            args '--entrypoint=""'
        }
    }
    steps {
        withCredentials([aws(accessKeyVariable: 'AWS_ACCESS_KEY_ID', credentialsId: 'reactAWS', secretKeyVariable: 'AWS_SECRET_ACCESS_KEY')]) {
            sh '''
                sed -i "s|IMAGE_PLACEHOLDER|$ECR_REPO:$BUILD_NUMBER|g" aws/task-definition.json
                aws ecs register-task-definition --cli-input-json file://aws/task-definition.json --region $AWS_DEFAULT_REGION
                aws ecs update-service --cluster $ECS_CLUSTER --service $ECS_SERVICE --task-definition react-jenkins-cicd --desired-count 1 --force-new-deployment --region $AWS_DEFAULT_REGION
            '''
        }
    }
}
    }

    post {
        success {
            echo "Pipeline completed successfully."
            cleanWs()
        }
        failure {
            echo "Pipeline failed. Check the logs above."
        }
    }
}
